  name: Waka Readme

  on:
    schedule:
      # Runs at 12AM EST
      - cron: '0 0 * * *'

  jobs:
    update-readme:
      name: Update Readme with Metrics
      runs-on: ubuntu-latest
      steps:
        - uses: anmol098/waka-readme-stats@master
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKA_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOK }}
            SHOW_PROJECTS: "False"
            SHOW_OS: "False"
            SYMBOL_VERSION: 1
            SHOW_LANGUAGE_PER_REPO: "True"
            SHOW_COMMIT: "True"
            SHOW_TOTAL_CODE_TIME: "True"
            SHOW_LINES_OF_CODE: "True"

